### ISSUE TITLE
UnsupportedContentTypeException is not being caught

### ISSUE THREAD

**Issue by amymok** [18F/ReVAL#40]
This exception is being used in `validate`, but it is not properly caught anywhere, which crashes the API.  This should be handled gracefully that propagates to the top level (i.e. 400 response)

**Comment by cantsin** [comment]
I don't think we need to do this anymore -- the parser_classes decorator automatically checks all the `media_type`s and rejects if no matches are found (with a `HTTP_415_UNSUPPORTED_MEDIA_TYPE` error). Closing, unless we can crash the API using another way.
