### ISSUE TITLE
KeyError at /data_ingest/upload/ 'error_code' when testing p02_budgets

### ISSUE THREAD

**Issue by pganesh** [18F/ReVAL#50]
Hi

Great app - was trying it on Django 2.2, had to tweak model definitions a little to get it working.

In any case, when trying/testing the p02_budgets, I uploaded a csv with all the required columns missing - this gives a Key Error as shown below

If I use your supplied b01.csv file, it worked fine as expected.

Please let me know if questions

I'm using SQLLite3 as a database by the way, just FYI

Environment:

Request Method: POST
Request URL: http://127.0.0.1:8000/data_ingest/upload/

Django Version: 2.2.2
Python Version: 3.6.4
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.sites',
 'allauth',
 'allauth.account',
 'crispy_forms',
 'django_userforeignkey',
 'django_filters',
 'rest_framework',
 'data_ingest',
 'users',
 'pages',
 'fileupload',
 'invoices',
 'budget_data_ingest']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django_userforeignkey.middleware.UserForeignKeyMiddleware']

Traceback:

File "C:\Users\PGanesh\Envs\myproject\lib\site-packages\django\core\handlers\exception.py" in inner
  34.             response = get_response(request)

File "C:\Users\PGanesh\Envs\myproject\lib\site-packages\django\core\handlers\base.py" in _get_response
  115.                 response = self.process_exception_by_middleware(e, request)

File "C:\Users\PGanesh\Envs\myproject\lib\site-packages\django\core\handlers\base.py" in _get_response
  113.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "C:\Users\PGanesh\Envs\myproject\lib\site-packages\django\contrib\auth\decorators.py" in _wrapped_view
  21.                 return view_func(request, *args, **kwargs)

File "c:\users\pganesh\envs\myproject\src\data-ingest\data_ingest\views.py" in upload
  104.             return validate(instance)

File "c:\users\pganesh\envs\myproject\src\data-ingest\data_ingest\views.py" in validate
  69.     instance.validation_results = ingestor.validate()

File "c:\users\pganesh\envs\myproject\src\data-ingest\data_ingest\ingestors.py" in validate
  827.         return apply_validators_to(self.source(), content_type)

File "c:\users\pganesh\envs\myproject\src\data-ingest\data_ingest\ingestors.py" in apply_validators_to
  49.         validation_results = validator.validate(source, content_type)

File "c:\users\pganesh\envs\myproject\src\data-ingest\data_ingest\ingestors.py" in validate
  655.                     output.add_row_error(rn, 'Error', rule['error_code'],

Exception Type: KeyError at /data_ingest/upload/
Exception Value: 'error_code'

**Comment by pganesh** [comment]
OK a quick update: I could fix by changing line 655 on ingestors.py to

                    output.add_row_error(rn, 'Error', rule.get('error_code'),

changed rule['error_code'] to rule.get('error_code')

**Comment by amymok** [comment]
@pganesh, thanks for bringing this up.  This is essentially the same issue as: https://github.com/18F/ReVAL/issues/41.

It sounds like you are able to move forward here?  We may not be able to fix the issue until a later time.  If you are interested, feel free to submit a PR with the proposed changes.  Thank you!

**Comment by pganesh** [comment]
Thanks Amy - we can wait on this

**Comment by cantsin** [comment]
We have upgraded to Django 2.2 and currently have a PR for this error -- thanks for the fix.
