### ISSUE TITLE
Rename ReVAL

### ISSUE THREAD

**Issue by cantsin** [18F/ReVAL#92]
We may want to get rid of `aggregation` in the acronym since ReVAL doesn't do aggregation anymore. 

We know we're done when:

- [x] We decide on a new name/acronym
- [ ] README.md has been updated
- [ ] Documentation has been updated

**Comment by cantsin** [comment]
@amymok any suggestions? Maybe just `reval` for now? 

```
reval (REusable VAlidation Library) is a Django App for validating data via an API and web interface.
```

Alternatively, we can forego the backronym:

```
reval (short for revalidator) is a Django App for validating data via an API and web interface.
```

**Comment by juliaklindpaintner** [comment]
I like keeping the "reusable" as a key part of the name, since its reusability was really the point. What about `ReVal`?

**Comment by amymok** [comment]
We can still keep all the letters in "reval" even by taking out the word "Aggregation". @cantsin is there any issue with having upper and lower case?

**Comment by cantsin** [comment]
No objections to upper/lower case. SGTM, let's do `ReVal`.
